In [209]:
import numpy as np

class ULS(object):
    def __init__(self, n, d, p, h, f):
        self.n = n
        self.d = d
        self.p = p
        self.h = h
        self.f = f
        self.c = self._calculate_c()
    
    def _calculate_c(self):
        c = [0] * self.n
        for i in range(self.n):
            c[i] = self.p[i] + sum(self.h[i:self.n-1])
        return c
    
    def calculate_H(self):
        H = [float('inf')] * self.n
        p = [0] * self.n
        for k in range(self.n):
            H[k] = self.f[0]+self.c[0]*sum(self.d[0:k+1])
            for t in range(1, k+1):
                value = H[t-1] + self.f[t]+self.c[t]*sum(self.d[t:k+1])
                if H[k] > value:
                    H[k] = value
                    p[k] = t
        return p
        
    def calculate_H_matrix(self):
        H = np.zeros((self.n, self.n))
        h_min = [float('inf')] * self.n
        for k in range(self.n):
            H[0][k] = self.f[0]+self.c[0]*sum(self.d[0:k+1])
            h_min[k] = H[0][k]
            for t in range(1, k+1):
                H[t][k] = h_min[t-1] + self.f[t]+self.c[t]*sum(self.d[t:k+1])
                if h_min[k] > H[t][k]:
                    h_min[k] = H[t][k]
        print(H)
    
    def calculate_xy(self):
        l = 0
        p = self.calculate_H()
        t = [0] * self.n
        y = [0] * self.n
        x = [0] * self.n
        t[l] = self.n
        while t[l] > 0:
            t[l+1] = p[self.n-l-1]
            y[t[l+1]] = 1
            x[t[l+1]] = sum(self.d[t[l+1]:t[l]])
            l+=1
        return (x,y)
    
    def do_something(self):
        print(self.n)
        

In [210]:
r = ULS(6,[3,2,5,3,7,1],[1,2,3,3,3,2],[2,1,1,1,2],[12,10,10,13,15,16])
print(r.c)
print(r.calculate_H())
r.calculate_H_matrix()
(x,y)= r.calculate_xy()
print(x,y)

[8, 7, 7, 6, 5, 2]
[0, 0, 0, 0, 1, 3]
[[  36.   52.   92.  116.  172.  180.]
 [   0.   60.   95.  116.  165.  172.]
 [   0.    0.   97.  118.  167.  174.]
 [   0.    0.    0.  123.  165.  171.]
 [   0.    0.    0.    0.  166.  171.]
 [   0.    0.    0.    0.    0.  183.]]
[3, 7, 0, 11, 0, 0] [1, 1, 0, 1, 0, 0]
